image:
  file: .gitpod.dockerfile
tasks:
  - command: redis-server --daemonize yes && export GITHUB_TOKEN=mKkLNrkKormlvZuouW7zzY9r8Modw70bNbkc && export GOPRIVATE=github.com/aghchan && export GOPROXY=direct && git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf https://github.com/
